overhangio/tutor-indigo

- theme/lms/templates/footer.html
For #1 
This patch updates the `footer.html` template so that the links defined in `config.yaml` render in the `/courses` pages.
It's quite possible this isn't the best way to resolve this issue - my edX theming knowledge is quite limited.
> Fixing footer links

- theme/lms/static/sass/partials/lms/theme/_extras.scss
On Safari for Macos the user menu is clipped due to a Safari bug. If you set both overflow:hidden and position:fixed on a parent element, a child element with position: fixed will incorrectly be clipped by the parent element. The fix for this is to remove overflow:visible on large screens, where it isn't required anyway.
> Fix for safari desktop

- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_extras.scss
The `#content.content-wrapper` style rule in `_extra.scss` is not specific enough, without this patch it will also affect course content inside MFE (inside the wrapping iframe), and couse a lot of extra white space and cut-off:
This patch only applies the style rules for `#content.content-wrapper` (in essence pushing this block down in case of a fixed header), if it follows a global header `header.global-header`, hence will not affect the html inside the MFE iframe.
> make lms .content-wrapper style rule more specific

- Makefile
- setup.py
- tutorindigo/plugin.py
*.scss files were not rendered at all in the tutor environment because they are
stored in a "partials" subdirectory.
Here, we make use of the new pattern include/ignore filter to force the
rendering of the indigo theme directory.
Close #24.
> fix: actually render scss files in tutor env

- README.rst
Adding the step `tutor config save` as this is what puts the indigo folder into the build environment.
> Add step to save configuration

- README.rst
In Tutor 16.0.2 in zsh, this command:
tutor config save --set "INDIGO_PRIMARY_COLOR=#225522"
will set `INDIGO_PRIMARY_COLOR` to `null` in config.yml. The same is true if double-quotes are used. If one wraps the color in additional set of quotes, though, then `INDIGO_PRIMARY_COLOR` is set without any issues.
I believe this is due to how the `#` is handled when rendering config.yml, but I haven't been able to dig into Tutor and confirm that. For now, I propose adding this example to this README in hope that it'll stop anyone from getting stuck on the `#` issue.
> docs: recommend nested quotes for setting primary color

- README.rst
- changelog.d/20240220_091010_misilot_remove_legal_links_mentions.md
- tutorindigo/plugin.py
It looks like INDIGO_FOOTER_NAV_LINKS is no longer used, so cleaning up the documentation
> Remove mentions of INDIGO_FOOTER_LEGAL_LINKS from documentation

- changelog.d/20240220_174954_talharizwan667_indigo_cms_scss.md
- tutorindigo/plugin.py
-  *.scss files in cms were not rendered at all in the tutor environment because they are stored in a "partials" subdirectory.
-  added override styling for cms using _variables.scss and _extras.scss
- added a customizable footer with styling as no custom footer was there for cms but for lms.
PR for #69
> fix: CMS render scss styling in tutor env 

- changelog.d/20240614_162236_codewithemad_cleanup.md
- tutorindigo/plugin.py
- tutorindigo/templates/indigo/lms/static/fonts/OFL.txt
- tutorindigo/templates/indigo/lms/static/sass/courseware/_discover.scss
- tutorindigo/templates/indigo/lms/static/sass/dashboard/_dashboard.scss
- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_extras.scss
- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_variables.scss
- tutorindigo/templates/indigo/lms/static/sass/programs/_programs.scss
- tutorindigo/templates/indigo/lms/templates/courseware/course_about.html
- tutorindigo/templates/indigo/lms/templates/courseware/courses.html
- tutorindigo/templates/indigo/lms/templates/dashboard.html
- tutorindigo/templates/indigo/lms/templates/dashboard/_dashboard_course_listing.html
- tutorindigo/templates/indigo/lms/templates/footer.html
- tutorindigo/templates/indigo/lms/templates/header/navbar-not-authenticated.html
- tutorindigo/templates/indigo/lms/templates/learner_dashboard/program_card.underscore
This will 
- Removes the force to using authn mfe for login and registration
- Removes trailing whitespaces
- Fixes some typos
> fix: let the platform decide for login and registration

- tutorindigo/plugin.py
- tutorindigo/templates/indigo/env.config.jsx
Issue:
With Tutor v18 and Tutor Indigo v18.1.0, users are unable to view the accounts page. Tutor Indigo v18.1.0 has installation of custom indigo header and footer in learning, dashboard, profile, discussion and account MFE. All MFEs are compatible with indigo header and footer except accounts MFE. The reason is:
In redwood:
**Most of the MFEs using  ----> footer v14**
- footer is installed via `@openedx/frontend-slot-footer package`
- footer is imported like `import FooterSlot from '@openedx/frontend-slot-footer'`;
**Account MFE -----> footer v13**
- footer is installed via `@edx/frontend-component-footer`
- footer is imported like `import { FooterSlot } from '@edx/frontend-component-footer';`
Our indigo footer is created from footer v14 and we are installing it in all MFEs (account MFE …
> fix: problem displaying /account/ page after upgraded to redwood

- changelog.d/20241205_225149_hina.khadim_ora_dark_theme_fixups.md
- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_variables.scss
- tutorindigo/templates/indigo/lms/static/sass/xblock/_xblock.scss
Fix multiple dark theme issues with ORA xblock
Closes (task 1 of) #107 
- <img width="1166" alt="image" src="https://github.com/user-attachments/assets/7de7bbf2-a0e8-4401-ad4c-4355b89598a1">
----------------------------------------------------------------------------------------------------------------
- <img width="1166" alt="image" src="https://github.com/user-attachments/assets/618c2fdd-fb4f-481f-b0b4-17726ee10662">
----------------------------------------------------------------------------------------------------------------
- <img width="1166" alt="image" src="https://github.com/user-attachments/assets/a1e6fae2-ef92-45c3-8537-ecfa8f9010a0">
----------------------------------------------------------------------------------------------------------------
- <img width="1166" alt="image" …
> fix: ORA dark theme compatibility updates

- changelog.d/20241206_184802_dawoud.sheraz_teams_tab_dark_theme_fixups.md
- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_extras.scss
Resolve a part of https://github.com/overhangio/tutor-indigo/issues/107 and https://github.com/openedx/wg-build-test-release/issues/410 -- fixes dark theme compatibility issues with Teams tab
> fix: fix various dark theme issues with Teams tab

- changelog.d/20241209_134456_hina.khadim_teams_notes_page.md
- tutorindigo/templates/indigo/lms/static/sass/partials/lms/theme/_extras.scss
- tutorindigo/templates/indigo/lms/static/sass/xblock/_xblock.scss
This PR adds dark-theme to notes and textbook page
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
[The white page of pdf is rendered via pdfViewer/Canvas. It cannot be converted to dark in dark-mode.]
> fix: add dark-theme to notes and textbook page

- .github/workflows/test.yml
- tutorindigo/patches/mfe-env-config-buildtime-definitions
- tutorindigo/patches/mfe-env-config-buildtime-imports
- tutorindigo/patches/mfe-env-config-runtime-definitions
- tutorindigo/plugin.py
Add env-patches to add code in `env.config.jsx` and updated plugin.py for updating footer_slot.
Update required for https://github.com/overhangio/tutor-mfe/pull/240
> fix: update env.config.jsx according to tutor-mfe#240 PR

- changelog.d/20250505_200616_ahmed.khalid_fix_mfe_footer_import.md
- tutorindigo/patches/mfe-env-config-runtime-definitions
- tutorindigo/plugin.py
This PR ensures that the Indigo footer component is only imported in MFEs that have the package installed. This avoids potential runtime errors in MFEs that do not include the `@edly-io/indigo-frontend-component-footer` dependency.
Unconditional installation of dependencies was breaking the plugin slots mechanism in tutor-mfe.
> fix: import footer only in supported MFEs

- changelog.d/20250505_200616_ahmed.khalid_fix_mfe_footer_import.md
- tutorindigo/patches/mfe-env-config-runtime-definitions
- tutorindigo/plugin.py
This PR brings changes from the release with conflict resolution.
Ref: https://github.com/overhangio/tutor-indigo/pull/148
> fix: footer import issue in unsupported MFEs

- tutorindigo/templates/indigo/lms/templates/header/header.html
The language switch dropdown in the Tutor Indigo theme was generating incorrect URLs due to the use of 'session_language' in `header.html`.
Replaced 'session_language' with 'update_language' in the `header.html` file to ensure correct URL generation for language switching.
- Enabled multiple languages in Open edX.
- Verified that the language switch dropdown now generates the correct URLs and functions as expected.
> fix: correct language switch URL in header.html

- tutorindigo/plugin.py
- tutorindigo/templates/indigo/lms/static/js/dark-theme.js
- tutorindigo/templates/indigo/lms/templates/header/theme-toggle-button.html
This PR enhances the **accessibility** of the **theme toggle switch** in the shared header component by improving how it is announced to screen readers. This update ensures users who rely on assistive technologies can understand the purpose of the toggle and interact with it effectively.
The change aligns with **WCAG Success Criterion 4.1.2 – Name, Role, Value**, which requires that user interface elements expose meaningful names and roles programmatically.
---
* **Actual Result:**
The theme toggle (used to switch between light and dark modes) did not have an accessible name. As a result, screen readers could not interpret or announce its function, making it difficult for visually impaired users to understand its purpose.
* **Expected Behaviour:**
The toggle should expose a descriptive …
> feat: enhance accessibility by adding descriptive label to theme toggle

- tutorindigo/templates/indigo/lms/templates/discovery/course_card.underscore
This pull request resolves several accessibility issues in the Tutor Indigo theme that were identified during a recent accessibility review. The updates aim to improve usability for all users, particularly those who rely on assistive technologies, while ensuring compliance with recognized accessibility standards such as the Web Content Accessibility Guidelines (WCAG) 2.1.
For further details, please refer to the related issue: [overhangio/tutor-indigo#146](https://github.com/overhangio/tutor-indigo/issues/146).
---
One specific improvement addresses the ambiguity of the **"Learn More"** links on the Courses page. Although the visible text remains unchanged to preserve the visual layout, screen reader–only text is added using the `<span class="sr-only">` element. This enhancement ensures …
> feat: Make 'Learn More' Links Screen Reader Accessible on Courses Page

- tutorindigo/plugin.py
- tutorindigo/templates/indigo/lms/templates/courseware/course_about.html
- tutorindigo/templates/indigo/lms/templates/courseware/course_about_sidebar_header.html
- tutorindigo/templates/indigo/lms/templates/discovery/course_card.underscore
This PR resolves an accessibility issue found on the **About Page** of the Tutor Indigo Theme, where the **Twitter**, **Facebook**, and **Email** icons did not have accessible names. This was flagged under **WCAG Success Criterion 1.1.1 – Non-text Content**, which requires that meaningful icons must provide a text alternative for assistive technologies.
For further details, please refer to the related issue: https://github.com/overhangio/tutor-indigo/issues/146.
---
* **Actual Result:**
The Twitter, Facebook, Email, and Calendar icons did not have accessible names, making them unreadable by screen readers.
The course images are decorative and have an alt text.
* **Expected Behaviour:**
These icons should have accessible names to clearly convey their purpose to screen reader users.
The …
> fix: Ensure decorative images do not interfere with screen readers

- tutorindigo/templates/indigo/lms/static/sass/extra/_header.scss
- tutorindigo/templates/indigo/lms/templates/courseware/course_about.html
- tutorindigo/templates/indigo/lms/templates/header/user_dropdown.html
This PR makes the **"Skip to content"** link styling to ensure a consistent and accessible experience across all pages.  
The update applies unified SCSS rules for the `.sr-only-focusable` class within the `header` element, ensuring the link is:
- Positioned consistently at the top center of the page  
- Clearly visible on focus with high contrast (black background, white text)  
- Readable and easily accessible for keyboard users  
**Taiga Task (if you have access):**  
- [Skip to main content](https://tree.taiga.io/project/zaraahmed-tutor-indigo-accessibility/us/43)
- [Consistent navigation](https://tree.taiga.io/project/zaraahmed-tutor-indigo-accessibility/us/81)
---
| Before | After |
| :--- | :---: |
| <img width="1620" height="654" alt="image" …
> fix: make 'skip to content' consistent
